kind: Deployment
apiVersion: apps/v1
metadata:
  name: result
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: result
          image: mgrillet/result:latest
          imagePullPolicy: Always
