kind: DeploymentConfig
apiVersion: apps/v1
metadata:
  name: worker
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: worker
          image: mgrillet/worker:latest
          imagePullPolicy: Always
